castDb:
  replicaCount: 1
  image:
    repository: postgres
    tag: 12.1-alpine
  env:
    POSTGRES_DB: cast_db_dev
    POSTGRES_PASSWORD: cast_db_password
    POSTGRES_USER: cast_db_username
  persistentVolumeClaim:
    name: postgres-data-cast
    storage: 100Mi
  service:
    port: 5432

castDb:
  replicaCount: 1
  image:
    repository: postgres
    tag: 12.1-alpine
  env:
    POSTGRES_DB: cast_db_dev
    POSTGRES_PASSWORD: cast_db_password
    POSTGRES_USER: cast_db_username
  persistentVolumeClaim:
    name: postgres-data-cast
    storage: 100Mi
  service:
    port: 5432

movieDb:
  replicaCount: 1
  image:
    repository: postgres
    tag: 12.1-alpine
  env:
    POSTGRES_DB: movie_db_dev
    POSTGRES_PASSWORD: movie_db_password
    POSTGRES_USER: movie_db_username
  persistentVolumeClaim:
    name: postgres-data-movie
    storage: 100Mi
  service:
    port: 5432

movieService:
  replicaCount: 1
  image:
    repository: dockerstudi/dts-exam-movie
    tag: "latest"
  env:
    CAST_SERVICE_HOST_URL: "http://cast_service:8000/api/v1/casts/"
    DATABASE_URI: "postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev"
  persistentVolumeClaim:
    name: movie-service-claim0
    storage: 100Mi
  service:
    port: 8001
    targetPort: 8000

nginx:
  replicaCount: 1
  image:
    repository: nginx
    tag: latest
  persistentVolumeClaim:
    name: nginx-claim0
    storage: 100Mi
  service:
    type: NodePort
    port: 8081
    targetPort: 8081
    nodePort: 30081

