apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.21.0 (992df58d8)
  name: {{ include "docker-compose.fullname" . }}-cast-service
  labels:
    app: {{ include "docker-compose.name" . }}-cast-service
spec:
  replicas: {{ .Values.castService.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "docker-compose.name" . }}-cast-service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.21.0 (992df58d8)
      labels:
        app: {{ include "docker-compose.name" . }}-cast-service
    spec:
      containers:
      - name: cast-service
        image: {{ .Values.castService.image.repository }}:{{ .Values.castService.image.tag }}
        imagePullPolicy: IfNotPresent
        args:
        - uvicorn
        - app.main:app
        - --reload
        - --host
        - 0.0.0.0
        - --port
        - "8000"
        env:
        - name: DATABASE_URI
          value: {{ .Values.castService.env.DATABASE_URI | quote }}
        ports:
        - containerPort: 8000
        volumeMounts:
        - mountPath: /app/
          name: cast-service-claim0
      restartPolicy: Always
      volumes:
      - name: cast-service-claim0
        persistentVolumeClaim:
          claimName: {{ .Values.castService.persistentVolumeClaim.name }}
