apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.castService.persistentVolumeClaim.name }}
  labels:
    app: {{ include "docker-compose.name" . }}-cast-service
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.castService.persistentVolumeClaim.storage }}
