apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Release.Namespace }}
data:
  nginx_config.conf: |-
    server {
      listen 8081;

      location /api/v1/movies {
        proxy_pass http://jenkins-datascientest-docker-compose-movie-service:8001/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://jenkins-datascientest-docker-compose-cast-service:8002/api/v1/casts;
      }
    }
