apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-compose.fullname" . }}-nginx
  labels:
    app: {{ include "docker-compose.name" . }}-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "docker-compose.name" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "docker-compose.name" . }}-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        ports:
        - containerPort: {{ .Values.nginx.service.port }}
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: nginx_config.conf
      volumes:
      - name: nginx-config
        persistentVolumeClaim:
          claimName: {{ .Values.nginx.persistentVolumeClaim.name }}