apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-compose.fullname" . }}-nginx
  labels:
    app: {{ include "docker-compose.name" . }}-nginx
spec:
  replicas: {{ .Values.nginx.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "docker-compose.name" . }}-nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ include "docker-compose.name" . }}-nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/nginx_config.conf
          subPath: nginx_config.conf
          name: nginx-config
      restartPolicy: Always
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
