apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nginx.persistentVolumeClaim.name }}
  labels:
    app: {{ include "docker-compose.name" . }}-nginx
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.nginx.persistentVolumeClaim.storage }}