apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-compose.fullname" . }}-nginx
  labels:
    app: {{ include "docker-compose.name" . }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081  # Ensure this NodePort is not used by any other service
    protocol: TCP
  selector:
    app: {{ include "docker-compose.name" . }}-nginx
