apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecrets.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  {{ .Values.dbSecrets.movieDbPasswordKey }}: {{ .Values.dbSecrets.movieDbPassword }}
  {{ .Values.dbSecrets.castDbPasswordKey }}: {{ .Values.dbSecrets.castDbPassword }}