apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbSecrets.name }}
  namespace: {{ .Values.namespace }}
  annotations:
   meta.helm.sh/release-name: {{ .Release.Name }}
   meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  {{ .Values.dbSecrets.movieDbPasswordKey }}: {{ .Values.dbSecrets.movieDbPassword }}
  {{ .Values.dbSecrets.castDbPasswordKey }}: {{ .Values.dbSecrets.castDbPassword }}